version: '3.8'

services:
    manager:
        build: ./manager
        ports:
            - "8080:8080"
        networks:
            - crackhash-net
        depends_on:
            - worker
    worker:
        build: ./worker
        networks:
            - crackhash-net

networks:
    crackhash-net:
        driver: bridge
        